config/routes.rb
Rails.application.routes.draw do
	root :to => "guitar#index"
	resources :guitar, :shallow => true do
		get "sellGuitar"
	end	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guitar.rb
class Guitar < ApplicationRecord
	validates :serial, uniqueness: true
	
	has_one :guitar_transaction
	has_one :guitar_accessory
end

app/models/guitar_accessory.rb
class GuitarAccessory < ApplicationRecord
	belongs_to :guitar
end

app/models/guitar_transaction.rb
class GuitarTransaction < ApplicationRecord
	belongs_to :guitar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/guitar_controller.rb
class GuitarController < ApplicationController
	def index
		@guitar = Guitar.new
	end	

	def create
		@newGuitar = Guitar.new(guitar_params) 
		@guitar_accessory = GuitarAccessory.new
		if params[:typeName] == "Acoustic"
			@guitar_accessory.guitarPick = "Wooden"
		else
		   	@guitar_accessory.guitarPick = "Plastic"
		end
		@newGuitar.guitar_accessory = @guitar_accessory
		@guitar_transaction = GuitarTransaction.new
		@guitar_transaction.buyDate = Date.today
		@newGuitar.guitar_transaction = @guitar_transaction   	
        @newGuitar.save
        redirect_to @newGuitar
	end

	def sellGuitar
		puts "Checking params inside sellGuitar ----- #{params.inspect}"
		guitar = Guitar.find(params[:id])	
		@guitar_transaction = guitar.guitar_transaction
		@guitar_accessory = guitar.guitar_accessory
		@guitar_transaction.sellDate = Date.today
		@guitar_accessory.strapType = params[:strapType]
		@guitar_transaction.save
		@guitar_accessory.save
		render :partial => "guitar/sold_guitar_template"
	end	

	def show
		@guitars = Guitar.all.order("created_at DESC")
	end
	
    private
	  def guitar_params
	    params.require(:guitar).permit(:brandName, :modelName, :typeName, :stringsNo, :price, :serial)
	  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guitar_helper.rb
module GuitarHelper
end

app/views/guitar/_new_guitar_form.html.erb
<div class= "parent-container">
  <%= form_for(@guitar, url: guitar_index_path, :html => { class: "form-inline", id: "new-guitar-create" }, method: 'POST') do |f| %>
 
    <div class="row"> 
      <div class="col">
        <%= f.label :brandName, 'Enter a Brand Name :   ' %> 
      </div>  
      <div class="col">
        <%= f.text_field :brandName, :class => 'form-control large-input-grp', :id => "guitar-brand-name-text", :placeholder => "Enter any Brand Name" %>
      </div>
      <div class="w-100"></div> 

      <div class="col">
        <%= f.label :modelName, 'Enter Model Name :   ' %> 
      </div>  
      <div class="col">
        <%= f.text_field :modelName, :class => 'form-control large-input-grp', :id => "guitar-model-name-text", :placeholder => "Enter any model name" %>
      </div>
      <div class="w-100"></div>  

      <div class="col">
        <%= f.label :typeName, 'Enter Guitar Type :   ' %>  
      </div>  
      <div class="col">
        <%= f.select :typeName, options_for_select(["Acoustic","Electric"]), {}, class: "form-control" %>
      </div>

      <div class="w-100"></div>  

      <div class="col">
        <%= f.label :stringsNo, 'Enter Strings :   ' %>  
      </div>  
      <div class="col">
        <%= f.number_field :stringsNo, :class => 'form-control large-input-grp', :id => "number-of-strings-text", :placeholder => "Enter No. of Strings" %>  
      </div>

      <div class="w-100"></div>  

      <div class="col">
        <%= f.label :price, 'Enter Price in INR:' %>  
      </div>  
      <div class="col">
        <%= f.number_field :price, :class => 'form-control large-input-grp', :id => "guitar-price-text", :placeholder => "Enter Price :" %>  
      </div>


      <div class="w-100"></div>  

      <div class="col">
        <%= f.label :serial, 'Enter Serial Number :   ' %>  
      </div>  
      <div class="col">
        <%= f.number_field :serial, :class => 'form-control large-input-grp', :id => "guitar-serial-number-text", :placeholder => "Enter Serial Number :" %>  
      </div>


      <br>
      <br>
      <div class="w-100">
        <span style="margin-left: 50%;">
          <%= button_tag(type: 'submit', class: "btn btn-success", id: "create_guitar_btn") do %>
          Create 
          <% end %>          
        </span>
       
      </div>
    </div>    
    
  <%end%>
</div>

app/views/guitar/_sold_guitar_template.html.erb
<p><h3 style="color: red;">This item is already sold on <%= @guitar_transaction.sellDate %> with the accessory <%= @guitar_accessory.strapType %></h3></p>

app/views/guitar/index.html.erb
<div class="container-fluid">
   <div class="row-fluid">
      <div style="margin-left: 23%;">
        <h3>Please take a moment to add a guitar in your inventory</h3>
      </div>
   </div>
</div>

<div class="container-fluid">
	<div class="row-fluid">
		<%= render "guitar/new_guitar_form" %>
	</div>
</div>   

app/views/guitar/show.html.erb
<div class="container-fluid">
   <div class="row-fluid">
      <div style="margin-left: 23%;">
        <h3>List of all the guitars in your inventory</h3>
      </div>
   </div>
</div>

<div class="container-fluid">
	<div class="row-fluid">
	    <% @guitars.each do |guitar| %>
			<div class="card" style="width: 20rem;">
			  <%= image_tag "misc/guitar-icon.jpg", height: '100', width: '100' %>
			  <div class="card-body" id= "guitar_card_<%= guitar.id %>">
			    <h4 class="card-title"><%= guitar.brandName %></h4>
			    <p class="card-text">The guitar <%= guitar.modelName %> with the serial number <h4><%= guitar.serial%></h4> is a premier <%= guitar.stringsNo %> string guitar. The guitar was bought on <h4><%= guitar.guitar_transaction.buyDate %></h4> The price of the guitar is <h4><%= guitar.price %></h4></p>
			    <span>
                   <%= select_tag "strap-type", options_for_select([ "Regular", "Large", "Extra Large"], "Regular")	%>		    
			    </span>
			    <span id="item-desc-<%=guitar.id %>">
				    <% if guitar.guitar_transaction.sellDate == nil %>
				      <a href="#" class="btn btn-danger" id="guitar-sell-btn-<%= guitar.id %>" onclick="javascript: sellGuitar('<%= guitar.id %>');">Sell</a>
				    <% else %>
				       <p><h3 style="color: red;">This item is already sold on <%= guitar.guitar_transaction.sellDate %></h3></p>
				    <% end %>  		    	
			    </span>
			    <span id="sold-item-desc-<%=guitar.id %>">
			    	
			    </span>


			  </div>
			</div>	
		<% end %>		
	</div>
</div>

<br>
<br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Guitar Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="cm-bg">
		<nav class="navbar navbar-default">
		  <div class="container-fluid">
		    <div class="navbar-header">
		      <a class="navbar-brand" href="#">
		        <%= image_tag "misc/images.jpg", height: '70', width: '170' %>
		      </a>
		    </div>
		      
		    <div>
		      <p class="text-left"><h1>Your personalised guitar store</h1></p>
		    </div>
		  </div>
		</nav>
	</div>	
	<%= yield %>


    <div class="cm-footer">
	    <footer class="footer">
	      <div class="container">
	        <span class="text-muted text-center" style="margin-left: 35%;"><h3>This is a sample project made for Memcorp Immersive Learning</h3></span>
	      </div>
	    </footer>	
    </div>

  </body>
</html>